version: "2.2"

services:
  mysql:
    image: mysql:5.7.20
    container_name: lab-mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./data/backup:/opt
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mrs

    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --max_allowed_packet=3G
    networks:
      - cloudbuild

networks:
  cloudbuild:
    name: cloudbuild
    driver: bridge